const SearchActionTypes = {
 FETCH_SEARCH_DATA_START: 'FETCH_SEARCH_DATA_START',
 FETCH_SEARCH_DATA_SUCCESS: 'FETCH_SEARCH_DATA_SUCCESS',
 FETCH_SEARCH_DATA_ERROR: 'FETCH_SEARCH_DATA_ERROR',
 SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
 SET_IMAGE_DATA: 'SET_IMAGE_DATA'
}

export default SearchActionTypes;