const ApodActionTypes = {
    SET_APOD_DATA_START: 'SET_APOD_DATA_START',
    SET_APOD_DATA_SUCCESS: 'SET_APOD_DATA_SUCCESS',
    SET_APOD_DATA_ERROR: 'SET_APOD_DATA_ERROR'
}

export default ApodActionTypes;